//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveLPBot.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveLPBot.Data.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\BlueprintMap.json.
        /// </summary>
        internal static string blueprintmap {
            get {
                return ResourceManager.GetString("blueprintmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure\db.config.
        /// </summary>
        internal static string dbconfig {
            get {
                return ResourceManager.GetString("dbconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\idnamemap.json.
        /// </summary>
        internal static string idnamemap {
            get {
                return ResourceManager.GetString("idnamemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\lpstore.json.
        /// </summary>
        internal static string lpstoredata {
            get {
                return ResourceManager.GetString("lpstoredata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\npcCorpsMap.json.
        /// </summary>
        internal static string npccorpsmap {
            get {
                return ResourceManager.GetString("npccorpsmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\universemap.json.
        /// </summary>
        internal static string universemap {
            get {
                return ResourceManager.GetString("universemap", resourceCulture);
            }
        }
    }
}
